### ISSUE TITLE
Can't open the files

### ISSUE THREAD

**Issue by LordLumineer** [Inochi2D/example-models#1]
Hello,
On the both session and creator I can't load the .inx or .psd, I tried on the 0.7.4 and 0.8 and it gave me the same errors.
But when creating a psd file from photoshop, there is no issues, also photoshop refuses to open the psd.

Thanks for your hard job.
.psd on photoshop
![psd-photoshop](https://user-images.githubusercontent.com/56554075/236018699-d681e9f4-585c-4fa7-bca2-89308e1dd309.PNG)
.inx on session (0.8)
![inx-session](https://user-images.githubusercontent.com/56554075/236018701-6d551ca1-92d1-410d-a402-c9b1f792c0e7.PNG)
.psd on creator (0.8)
![psd-creator](https://user-images.githubusercontent.com/56554075/236018704-c52153eb-7b67-451b-bdda-9071cb8a8bcc.PNG)
.inx on creator (0.8)
![inx-creator](https://user-images.githubusercontent.com/56554075/236018709-c716aac8-0b83-4af1-9b58-3ed4e597b722.PNG)

**Comment by LordLumineer** [comment]
There was an issue with the default .ZIP download not downloading properly the files, I had to clone it through GLF.

**Comment by LunaTheFoxgirl** [comment]
You are not supposed to clone this repository, you're supposed to download these files on the same page you download creator or session.

Eventually I might make this repository private since it's just meant to host the files for us to package them up properly.
