### ISSUE TITLE
Invalid data format for Inochi Creator INX in 0.8.2

### ISSUE THREAD

**Issue by sanket143** [Inochi2D/example-models#3]
downloaded the app from itch.io https://lunafoxgirlvt.itch.io/inochi-creator

Inochi creator: v0.8.2
I2D v0.8.3
imgui  v1.88 WIP

![image](https://github.com/Inochi2D/example-models/assets/26973649/75925d32-b4fe-443d-8fbe-86da0f0c6b64)

**Comment by LunaTheFoxgirl** [comment]
Models in this repository are git LFS files, they won't be useful to you, please download the example models from the actual Inochi Creator download page on itch.
